FROM nginx:alpine

# Копируем конфиги
COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/

# Создаем папку для SSL (на всякий случай)
RUN mkdir -p /etc/nginx/ssl

# Копируем SSL сертификаты (если они в образе)
# COPY ssl/ /etc/nginx/ssl/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]